### PR TITLE
feat(dashboard): new design for dashboard

### LINKED ISSUE #2: Should the default dashboard be named "Dashboard"?
Currently the pre-provisioned dashboard is named, well, *Dashboard*. Should this be ex. *Cryostat* instead?

### LINKED ISSUE #11: [Task] Redesign Grafana Dashboard
The Grafana Dashboard has't been updated and needs redesigning to support new events. Here are some of the things to look into:
- [x] Categorize panels according to events. This will be easier for extension.
- [x] Fix unit display.
- [x] Larger default time frame.
- [x] Rename dashboard to `Cryostat` or probably the recording name #2 
- [x] Clean up unused fields (i.e. hashKey generated by Grafana)
- [x] Support separate dashboard with filters for jdk.ObjectAllocationSample
- [x] Each "sub" dashboard should have direct link back to the Main Dashboard.
- [x] Dashboard should default to open main Cryostat Dashboard on launch.

**Datasource task:**
- [ ] https://github.com/cryostatio/jfr-datasource/issues/128
- [ ] https://github.com/cryostatio/jfr-datasource/issues/62
- [ ] https://github.com/cryostatio/jfr-datasource/issues/129
- [ ] https://github.com/cryostatio/jfr-datasource/issues/130
- [ ] https://github.com/cryostatio/jfr-datasource/issues/78
- [ ] https://github.com/cryostatio/jfr-datasource/issues/134

### PR DESCRIPTION
**Pull request by tthvo**
Fixes #11 
Fixes #2 
Depends on https://github.com/cryostatio/jfr-datasource/pull/135

**What's new?**

- Main dashboard name is now `Cryostat Dashboard`.
- Events are placed in their respective categories.
- Graph now displays correct units (i.e. no more ~23 PETAbytes memory usage :d)
- Default time frame is set to `24h-ago <-> now`.
- A separate dashboard with filters for jdk.ObjectAllocationSample.
- Each "sub" dashboard should have direct link back to the Main Dashboard.
- Dashboard will open main Cryostat Dashboard on launch.
- Duration and Start time of recording is fixed for any time frame of a single recording. See [comment](https://github.com/cryostatio/jfr-datasource/issues/134#issuecomment-1261390548).

### CODE REVIEW

**Comment by tthvo** [comment]
> Default time frame is set to 1-year-ago - now.

This just ensures the data is visible at least until this feature https://github.com/grafana/grafana/issues/6288 is implemented :D

**Comment by tthvo** [comment]
> There's still a Zoom Out button near the top right corner of the dashboard screen, right? If so, I think a narrower default time range would be better. A year-long JFR file would probably be prohibitively large in size and unlikely to load at all. I think just the past hour would be a better middleground default. Good chance the recording is shorter so the user needs to zoom in somewhat, but it may also be somewhat longer so the user might need to zoom out using the top date range toolbar controls.

Right! That makes sense! Then, I restore it back to last 24-h as we had previously.

**Comment by tthvo** [comment]
The corresponding datasource PR just needs tests fixed so I think you can test them out.

**Review by andrewazores — APPROVED** [review]
Fantastic work.

**Review by maxcao13 — APPROVED** [review]
Awesome job, looks great!

**Pull request merged**
